### PR TITLE
Update harbour-slumber-es.ts

### PR DESCRIPTION
**Pull request by ghost**
fixed some words.        (   ((  (((  (((( jgibbon ))))  )))  ))  ) the best.
i will fix some words y translate in TALEFISH too.

### CODE REVIEW

**Comment by jgibbon** [comment]
Hey, thanks @Caballlero!
What was wrong with it? 
If the existing text was "too argentinian" for you (@CepiPerez is from argentina AFAIK), I'll add es_ar as a language with the old strings and merge your pull request later as es_es. This way we have both.
If it's only a matter of taste, I'll just merge it.

**Comment by ghost** [comment]
-Not  was that his translation very argentinian Only that he passed some untranslated words and some small mistakes.
-I just check the translation he made,and see some words not translated Or forgetting
-If you want to cancel my request, there is no problem. I did it because you added me as a translator to Spanish to slumber in transifex. so I am supporting you in your projects as best as possible.
->>>>I do not think it necessary to create es-ar, because I am not altering its translation very much, it is only small details that remain after the first translation<<<<<<<<, i followed he same  structure to translate. If you accept the request, please do not mention me.if would be better   :)

i speaking same idiom with cepi - Besides he is no longer active here to ask him. :  (

**Comment by CepiPerez** [comment]
Hello. I agree with all changes, except for "Usted". It should be caps, not only for my country. Also "sacudida" doesn't sound good, maybe it's better to change to "al sacudir".

**Comment by jgibbon** [comment]
Thanks, both of you, for the effort and taking the time! Very much appreciated! :)

@Caballlero what do you think about "Usted" and "sacudida"? 
I'll leave it in your hands to update or leave it as you please before I'll merge this and transfer it to transifex.

**Comment by ghost** [comment]
Como así caps cepi?
 Y sobre porque escribí sacudida, es porque la frase que estaba antes era muy larga, y era incapaz de leer todo el texto en modo pantalla vertical, sobre jolla Phone y jolla c, entonces rápidamente incorpore una palabra que cabiera en toda la pantalla modo vertical en todas las pantallas.

**Comment by ghost** [comment]
Y si talvez sacudir este mejor que sacudida. Voy a subir un pantallazo sobre cómo se ve sobre la frase que acorte con sacudida, que teléfono tiene usted cepi?  Oh ya te salistes de pez vela?

**Comment by jgibbon** [comment]
Note (if google translate made me understand correctly): 
If some words don't fit, I'd be delighted to fix the layout if possible! 
~~Please file a bug and attach a screenshot. ;)~~

Thanks!

EDIT: Ok, I've switched to spanish and found it. That's in a standard SFOS Component. ~~I'll see what I can  do about that later today.~~
EDIT2: It might be better to change the text, after all :( sorry for confusion

**Comment by ghost** [comment]
captura_20170124_001

**Comment by jgibbon** [comment]
@Caballlero Another Idea: Since the long text only is visible with the first option… is there a way to split up the text differently that would make sense? (Putting more text in front of "apagado" instead of the title)

Thanks, again, for your efforts! Really cool!

**Comment by ghost** [comment]
As this is my request it gets fixed  by itself because I shorten the text exept by a word that I put cepi does not agree, I'm checking that word to see if cepi is right.

**Comment by ghost** [comment]
-I made a change that cepi mentioned and is really right. > "al sacudir" it is much better that "sacudida"
-Also he mentioned something about caps, and I asked him what CAPS refers to but he does not answer me, you know that @jgibbon ?
-May be He referred to start the first capital letter on a sentence(caps), because as I did there is a capital letter at the beginning of the phrase that cepi mentions, maybe did not see well and is wrong
# Just waiting for the complete approval of cepi...

**Comment by jgibbon** [comment]
Yes, he meant capital letters. 

I took the time to investigate, because I'm a nerd like that: Usted means "you" and is handled exactly like in my language, german, with the word "Sie": Normally it's not capitalized, so most people nowadays don't remember that it's more polite (but a bit old-fashioned) to actually do capitalize it (for example when writing a letter).

**Comment by CepiPerez** [comment]
Usted always caps. I know it's not common, but you can check in Spanish Academy. I don't know who was the "genius" who made it, but maybe you can check in other apps. About "sacudida" (shake) I'm ok, if it fits better then go ahead. Thanks for asking guys.

**Comment by CepiPerez** [comment]
PS: Jolla phones doesn't work here with 3G/4G networks, that's why I'm only using Sailfish as a secondary rom in my Nexus 5, wich is pretty outdated. I'm waiting for Jolla to make a compatible device to come back to development. Regards!

**Comment by ghost** [comment]
+ thanks @jgibbon  for your research and try to help us. IT COOL.
+ I already made the change in favor of :
# MATIAS PEREZ | READY TO MERGE > 946d977

**Comment by ghost** [comment]
+ I hope it solves the problem of 3G/4G for your sailfish device, your contribution is MUCH NEEDED  @CepiPerez 
+ Have nice days GUYS ...

**Comment by jgibbon** [comment]
Thanks, guys! Will publish this later this week on openrepos…

**Pull request merged**
